src/Entity/Pos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PosRepository")
 */
class Pos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PosManager", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Manager;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Partner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getManager(): ?PosManager
    {
        return $this->Manager;
    }

    public function setManager(PosManager $Manager): self
    {
        $this->Manager = $Manager;

        return $this;
    }

    public function getPartner(): ?User
    {
        return $this->Partner;
    }

    public function setPartner(?User $Partner): self
    {
        $this->Partner = $Partner;

        return $this;
    }
}

src/Entity/PosManager.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PosManagerRepository")
 */
class PosManager
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $BirthDate;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $NIC;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Address;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): self
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->BirthDate;
    }

    public function setBirthDate(string $BirthDate): self
    {
        $this->BirthDate = $BirthDate;

        return $this;
    }

    public function getNIC(): ?string
    {
        return $this->NIC;
    }

    public function setNIC(string $NIC): self
    {
        $this->NIC = $NIC;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }
}

src/Controller/Pos/ManagerController.php
<?php

namespace App\Controller\Pos;

use App\Entity\Pos;
use App\Entity\PosManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ManagerController extends AbstractController
{
    /**
     * @Route("/pos/manager/list", name="manager_list")
     */
    public function managerList()
    {
        $managerList = $this->getDoctrine()->getRepository(PosManager::class)->findAll();
        return $this->render('pos/manager/index.html.twig', [
            'managerList' => $managerList
        ]);
    }
    /**
     * @Route("/pos/manager/add", name="manager_add")
     */
    public function managerAdd(Request $request)
    {
        if($request->getMethod() == 'POST'){
            $data = $request->request->all();
            $posManager = New PosManager();
            $posManager->setName($data['name']);
            $posManager->setSurname($data['surName']);
            $posManager->setBirthDate($data['birth']);
            $posManager->setAddress($data['address']);
            $posManager->setEmail($data['email']);
            $posManager->setNIC($data['nic']);
            $em = $this->getDoctrine()->getManager();
            $em->persist($posManager);
            $em->flush();
            echo '<script>alert("New Pos Manager has been added")</script>';
        }
        $managerList = $this->getDoctrine()->getRepository(PosManager::class)->findAll();
        return $this->render('pos/manager/add.html.twig', [
            'managerList' => $managerList
        ]);
    }
    /**
     * @Route("/pos/availabilities/check/{id},{name}", name="manager_availabilities_check")
     */
    public function managerAvailabilitiesCheck($id,$name){
        $check = $this->getDoctrine()->getRepository(Pos::class)->findOneBy(['Manager' => $id]);
        if (empty($check)){
            return new Response('<option value="'.$id.'">'.$name.'</option>');
        }else{
            return new Response('');
        }
    }
}

src/Controller/Pos/PosController.php
<?php

namespace App\Controller\Pos;

use App\Entity\Pos;
use App\Entity\PosManager;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PosController extends AbstractController
{
    /**
     * @Route("/pos/list", name="pos_list")
     */
    public function posList()
    {
        $posList = $this->getDoctrine()->getRepository(Pos::class)->findAll();
        return $this->render('pos/pos/index.html.twig', [
            'posList' => $posList,
        ]);
    }
    /**
     * @Route("/pos/add", name="pos_add")
     */
    public function posAdd(Request $request)
    {
        if($request->getMethod() == 'POST'){
            $data = $request->request->all();
            $pos = New Pos();
            $pos->setName($data['name']);
            $pos->setAddress($data['address']);
            $pos->setTel($data['tel']);
            $pos->setManager($this->getDoctrine()->getRepository(PosManager::class)->find($data['manager']));
            $pos->setPartner($this->getDoctrine()->getRepository(User::class)->find($data['partner']));
            $em = $this->getDoctrine()->getManager();
            $em->persist($pos);
            $em->flush();
            echo '<script>alert("New Pos has been added")</script>';
        }
//
//        $posList = $this->getDoctrine()->getRepository(Pos::class)->findAll();
        $managers = $this->getDoctrine()->getRepository(PosManager::class)->findAll();
        $repository = $this->getDoctrine()
            ->getRepository(User::class);
        $query = $repository->createQueryBuilder('p')
            ->where('p.roles LIKE :price')
            ->setParameter('price', '%ROLE_PARTNER%')
            ->getQuery();

        $partner = $query->getResult();
        return $this->render('pos/pos/add.html.twig', [
            'managers' => $managers,
            'partner' => $partner
        ]);
    }
}

templates/pos/pos/add.html.twig
{% extends 'base.html.twig' %}
{% block posActive %}
    {% block posAddActive %}
        active
    {% endblock %}
{% endblock %}
{% block title %}POS Add{% endblock %}
{% block stylesheets %}
{% endblock %}
{% block section %}
<div class="row">
    <!-- left column -->
    <div class="col-md-6 col-md-offset-3">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">POS Add</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="post">
                <div class="box-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" required class="form-control" name="name" placeholder="Enter name">
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" required class="form-control" name="address"  placeholder="Address">
                    </div>
                    <div class="form-group">
                        <label>Tel</label>
                        <input type="text" required class="form-control" name="tel" placeholder="Tel">
                    </div>
                    <div class="form-group">
                        <label>Assign Manager</label>
                        <select class="form-control" name="manager">
                            {% for i in managers %}
                                {{ render(controller(
                                    'App\\Controller\\Pos\\ManagerController::managerAvailabilitiesCheck',
                                    { 'id': i.id, 'name': i.name }
                                )) }}
{#                            <option>{{ i.name }} , {{ i.surname }}</option>#}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Assign Partner</label>
                        <select class="form-control" name="partner">
                            {% for i in partner %}
                            <option value="{{ i.id }}">{{ i.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
{% endblock %}

templates/pos/pos/index.html.twig
{% extends 'base.html.twig' %}
{% block posActive %}
    {% block posListActive %}
        active
    {% endblock %}
{% endblock %}
{% block title %}POS List{% endblock %}
{% block stylesheets %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
{% endblock %}
{% block section %}
<div class="box">
    <div class="box-header">
        <h3 class="box-title">POS List </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>SR#</th>
                <th>Name</th>
                <th>Address</th>
                <th>Tel</th>
                <th>Manager</th>
                <th>Partner</th>
            </tr>
            </thead>
            <tbody>
            {% for i in posList %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ i.name }}</td>
                <td>{{ i.address }}</td>
                <td>{{ i.tel }}</td>
                <td>{{ i.manager.name }}</td>
                <td>{{ i.partner.name }}</td>
            </tr>
            {% endfor %}
            </tbody>
{#            <tfoot>#}
{#            <tr>#}
{#                <th>Rendering engine</th>#}
{#                <th>Browser</th>#}
{#                <th>Platform(s)</th>#}
{#                <th>Engine version</th>#}
{#                <th>CSS grade</th>#}
{#            </tr>#}
{#            </tfoot>#}
        </table>
    </div>
    <!-- /.box-body -->
</div>
{% endblock %}
{% block javascripts %}
    <!-- DataTables -->
    <script src="{{ asset('') }}bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('') }}bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
{% endblock %}