src/Entity/SaleMan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SaleManRepository")
 */
class SaleMan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SurName;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $BirthDate;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $NIC;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $PhoneNumber;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Localisation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurName(): ?string
    {
        return $this->SurName;
    }

    public function setSurName(string $SurName): self
    {
        $this->SurName = $SurName;

        return $this;
    }

    public function getBirthDate(): ?string
    {
        return $this->BirthDate;
    }

    public function setBirthDate(string $BirthDate): self
    {
        $this->BirthDate = $BirthDate;

        return $this;
    }

    public function getNIC(): ?string
    {
        return $this->NIC;
    }

    public function setNIC(string $NIC): self
    {
        $this->NIC = $NIC;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(string $PhoneNumber): self
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(?string $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }
}

src/Controller/Sale/SaleManController.php
<?php

namespace App\Controller\Sale;

use App\Entity\SaleMan;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SaleManController extends AbstractController
{
    /**
     * @Route("/sale/saleman/list", name="sale_sale_man_list")
     */
    public function index()
    {
        $saleManList = $this->getDoctrine()->getRepository(SaleMan::class)->findAll();
        return $this->render('sale/sale_man/index.html.twig', [
            'saleManList' => $saleManList,
        ]);
    }

    /**
     * @Route("/sale/saleman/add", name="sale_sale_man_add")
     */
    public function saleManAdd(Request $request){
        if($request->getMethod() == 'POST'){
            $data = $request->request->all();
            $saleMan = New SaleMan();
            $saleMan->setName($data['name']);
            $saleMan->setSurName($data['surName']);
            $saleMan->setBirthDate($data['birth']);
            $saleMan->setNIC($data['nic']);
            $saleMan->setPhoneNumber($data['phoneNumber']);
            $saleMan->setEmail($data['email']);
            $saleMan->setAddress($data['address']);
            $saleMan->setType($data['type']);
            if($data['type'] == 'adhoc'){
                $saleMan->setLocalisation($data['localisation']);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($saleMan);
            $em->flush();
            echo '<script>alert("New sale man has been added")</script>';
        }
        return $this->render('sale/sale_man/add.html.twig');
    }
}

templates/sale/sale_man/add.html.twig
{% extends 'base.html.twig' %}
{% block saleMan %}
    {% block saleManAdd %}
        active
    {% endblock %}
{% endblock %}
{% block title %}Sale Man Add{% endblock %}
{% block stylesheets %}
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="{{ asset('') }}bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
{% endblock %}
{% block section %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-6 col-md-offset-3">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Sale Man</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" onsubmit="add(event)">
                    <div class="box-body">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" required class="form-control" name="name" placeholder="Enter name">
                        </div>
                        <div class="form-group">
                            <label>SurName</label>
                            <input type="text" required class="form-control" name="surName" placeholder="Enter surname">
                        </div>
                        <div class="form-group">
                            <label>Date of birth</label>
                            <input type="text" class="form-control pull-right" data-date-format="dd/mm/yyyy" placeholder="Date of birth" name="birth" id="datepicker">
                        </div>
                        <div class="form-group">
                            <label>NIC</label>
                            <input type="number" required class="form-control" name="nic" placeholder="National ID Card">
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" required class="form-control" name="phoneNumber" placeholder="Your phone number">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" required class="form-control" name="email" placeholder="Your email">
                        </div>
                        <div class="form-group">
                            <label>Current Address</label>
                            <input type="text" required class="form-control" name="address" placeholder="Current Address">
                        </div>
                        <div class="form-group">
                            <div class="radio">
                                <label>
                                    <input class="type" type="radio" name="type"  value="adhoc" checked>
                                    Adhoc Office
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input class="type" type="radio" name="type"  value="sale">
                                    Sale representative
                                </label>
                            </div>
                        </div>
                        <div class="form-group localisation">
                            <label>localisation</label>
                            <input type="text" class="form-control localisationValue" name="localisation" placeholder="localisation">
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <!-- bootstrap datepicker -->
    <script src="{{ asset('') }}bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script>
        function add(e){
            if (type === 'adhoc'){
                if($('.localisationValue').val() === ''){
                    alert('check your form');
                    e.preventDefault();
                }
            }
        }
        let type = 'adhoc';
        $('#datepicker').datepicker({
            autoclose: true,
        });
        $(document).ready(function () {
            $('.type').change(function () {
                type = this.value;
                if (type === 'sale'){
                    $('.localisation').addClass('hide');
                }else {
                    $('.localisation').removeClass('hide');
                }
            })
        })
    </script>
{% endblock %}

templates/sale/sale_man/index.html.twig
{% extends 'base.html.twig' %}
{% block saleMan %}
    {% block saleManList %}
        active
    {% endblock %}
{% endblock %}
{% block title %}Manager List{% endblock %}
{% block stylesheets %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
{% endblock %}
{% block section %}
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">SaleMan List </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>SR#</th>
                    <th>Name</th>
                    <th>SurName</th>
                    <th>Phone Number</th>
                    <th>Birth Date</th>
                    <th>NIC</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Type</th>
                    <th>localisation</th>
                </tr>
                </thead>
                <tbody>
                {% for i in saleManList %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ i.name }}</td>
                        <td>{{ i.surName }}</td>
                        <td>{{ i.phoneNumber }}</td>
                        <td>{{ i.birthDate }}</td>
                        <td>{{ i.nIC }}</td>
                        <td>{{ i.email }}</td>
                        <td>{{ i.address }}</td>
                        <td>{{ i.type }}</td>
                        <td>{{ i.localisation }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
{% endblock %}
{% block javascripts %}
    <!-- DataTables -->
    <script src="{{ asset('') }}bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('') }}bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
{% endblock %}