src/Entity/Partner.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartnerRepository")
 */
class Partner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $NameOfEntity;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $SectorOfEntity;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Function;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $PhoneNumber;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameOfEntity(): ?string
    {
        return $this->NameOfEntity;
    }

    public function setNameOfEntity(string $NameOfEntity): self
    {
        $this->NameOfEntity = $NameOfEntity;

        return $this;
    }

    public function getSectorOfEntity(): ?string
    {
        return $this->SectorOfEntity;
    }

    public function setSectorOfEntity(string $SectorOfEntity): self
    {
        $this->SectorOfEntity = $SectorOfEntity;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getFunction(): ?string
    {
        return $this->Function;
    }

    public function setFunction(string $Function): self
    {
        $this->Function = $Function;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(string $PhoneNumber): self
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $SurName;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurName(): ?string
    {
        return $this->SurName;
    }

    public function setSurName(string $SurName): self
    {
        $this->SurName = $SurName;

        return $this;
    }
}

src/Controller/Partner/PartnerController.php
<?php

namespace App\Controller\Partner;

use App\Entity\Partner;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PartnerController extends AbstractController
{
    /**
     * @Route("/partner/list", name="partner_list")
     */
    public function index()
    {
        $partnerList = $this->getDoctrine()->getRepository(Partner::class)->findAll();
        return $this->render('partner/partner/index.html.twig', [
            'partnerList' => $partnerList,
        ]);
    }
    /**
     * @Route("/partner/add", name="partner_add")
     */
    public function partnerAdd(Request $request){
        if($request->getMethod() == 'POST'){
            $data = $request->request->all();
            if(!empty($this->getDoctrine()->getRepository(User::class)->findOneBy(['email' => $data['email']]))){
                echo '<script>alert("Email already exist")</script>';
            }else {
                $user = New User();
                $user->setEmail($data['email']);
                $user->setName($data['name']);
                function randomPassword() {
                    $alphabet = 'abcdefghijklmnopqrstuvwxyz1234567890';
                    $pass = array(); //remember to declare $pass as an array
                    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
                    for ($i = 0; $i < 8; $i++) {
                        $n = rand(0, $alphaLength);
                        $pass[] = $alphabet[$n];
                    }
                    return implode($pass); //turn the array into a string
                }
                $user->setPlainPassword(randomPassword());
                $user->setUsername($data['email']);
                $user->setEnabled(true);
                $em = $this->getDoctrine()->getManager();
                $partner = New Partner();
                $partner->setAddress($data['address']);
                $partner->setNameOfEntity($data['nameOfEntity']);
                $partner->setSectorOfEntity($data['sectorOfActivity']);
                $partner->setPhoneNumber($data['phoneNumber']);
                $partner->setFunction($data['function']);
                $partner->setUser($user);
                $em->persist($user);
                $em->persist($partner);
                $em->flush();
                echo '<script>alert("New Partner has been added")</script>';
            }
        }
        return $this->render('partner/partner/add.html.twig');
    }
}

templates/partner/partner/add.html.twig
{% extends 'base.html.twig' %}
{% block partner %}
    {% block partnerAdd %}
        active
    {% endblock %}
{% endblock %}
{% block title %}Partner Add{% endblock %}
{% block stylesheets %}
{% endblock %}
{% block section %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-6 col-md-offset-3">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Partner Add</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label>Name of entity</label>
                            <input type="text" required class="form-control" name="nameOfEntity" placeholder="Name of entity">
                        </div>
                        <div class="form-group">
                            <label>Sector of activity</label>
                            <input type="text" required class="form-control" name="sectorOfActivity"  placeholder="Sector of activity">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input type="text" required class="form-control" name="address" placeholder="Address">
                        </div>
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" required class="form-control" name="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" required class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label>Function</label>
                            <input type="text" required class="form-control" name="function" placeholder="Function">
                        </div>
                        <div class="form-group">
                            <label>Phone number</label>
                            <input type="text" required class="form-control" name="phoneNumber" placeholder="Phone number">
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
{% endblock %}

templates/partner/partner/index.html.twig
{% extends 'base.html.twig' %}
{% block partner %}
    {% block partnerList %}
        active
    {% endblock %}
{% endblock %}
{% block title %}Partner List{% endblock %}
{% block stylesheets %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
{% endblock %}
{% block section %}
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Partner List </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>SR#</th>
                    <th>Name</th>
                    <th>SurName</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Name Of entity</th>
                    <th>Sector of entity</th>
                    <th>Address</th>
                    <th>Function</th>
                </tr>
                </thead>
                <tbody>
                {% for i in partnerList %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ i.user.name }}</td>
                        <td>{{ i.user.surName }}</td>
                        <td>{{ i.phoneNumber }}</td>
                        <td>{{ i.user.email }}</td>
                        <td>{{ i.nameOfEntity }}</td>
                        <td>{{ i.sectorOfEntity }}</td>
                        <td>{{ i.address }}</td>
                        <td>{{ i.function }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
{% endblock %}
{% block javascripts %}
    <!-- DataTables -->
    <script src="{{ asset('') }}bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{ asset('') }}bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#example1').DataTable()
        })
    </script>
{% endblock %}